//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.ASMXServiceLab4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sde/", ConfigurationName="ASMXServiceLab4.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (sum) of message sum does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Forms.ASMXServiceLab4.sum1 Add(Forms.ASMXServiceLab4.sum request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sum", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sum1> AddAsync(Forms.ASMXServiceLab4.sum request);
        
        // CODEGEN: Generating message contract since the wrapper name (concat) of message concat does not match the default value (Concat)
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/concat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Forms.ASMXServiceLab4.concat1 Concat(Forms.ASMXServiceLab4.concat request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/concat", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.concat1> ConcatAsync(Forms.ASMXServiceLab4.concat request);
        
        // CODEGEN: Generating message contract since the wrapper name (sumA) of message sumA does not match the default value (Sum)
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sumA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Forms.ASMXServiceLab4.sumA1 Sum(Forms.ASMXServiceLab4.sumA request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sumA", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumA1> SumAsync(Forms.ASMXServiceLab4.sumA request);
        
        // CODEGEN: Generating message contract since the wrapper name (sumjson) of message sumjson does not match the default value (Adds)
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sumjson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Forms.ASMXServiceLab4.sumjson1 Adds(Forms.ASMXServiceLab4.sumjson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/sumjson", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumjson1> AddsAsync(Forms.ASMXServiceLab4.sumjson request);
        
        // CODEGEN: Generating message contract since the wrapper name (getjsonA) of message getjsonA does not match the default value (GetA)
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/getjsonA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Forms.ASMXServiceLab4.getjsonA1 GetA(Forms.ASMXServiceLab4.getjsonA request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sde/getjsonA", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.getjsonA1> GetAAsync(Forms.ASMXServiceLab4.getjsonA request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sum", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sum {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=1)]
        public int y;
        
        public sum() {
        }
        
        public sum(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumResponse", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sum1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public int sumResult;
        
        public sum1() {
        }
        
        public sum1(int sumResult) {
            this.sumResult = sumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concat", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class concat {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=1)]
        public double d;
        
        public concat() {
        }
        
        public concat(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="concatResponse", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class concat1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public string concatResult;
        
        public concat1() {
        }
        
        public concat1(string concatResult) {
            this.concatResult = concatResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sde/")]
    public partial class A : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sField;
        
        private int kField;
        
        private float fField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string s {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
                this.RaisePropertyChanged("s");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
                this.RaisePropertyChanged("k");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
                this.RaisePropertyChanged("f");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumA", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sumA {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public Forms.ASMXServiceLab4.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=1)]
        public Forms.ASMXServiceLab4.A a2;
        
        public sumA() {
        }
        
        public sumA(Forms.ASMXServiceLab4.A a1, Forms.ASMXServiceLab4.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumAResponse", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sumA1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public Forms.ASMXServiceLab4.A sumAResult;
        
        public sumA1() {
        }
        
        public sumA1(Forms.ASMXServiceLab4.A sumAResult) {
            this.sumAResult = sumAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumjson", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sumjson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=1)]
        public int y;
        
        public sumjson() {
        }
        
        public sumjson(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumjsonResponse", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class sumjson1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public int sumjsonResult;
        
        public sumjson1() {
        }
        
        public sumjson1(int sumjsonResult) {
            this.sumjsonResult = sumjsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getjsonA", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class getjsonA {
        
        public getjsonA() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getjsonAResponse", WrapperNamespace="http://sde/", IsWrapped=true)]
    public partial class getjsonA1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sde/", Order=0)]
        public Forms.ASMXServiceLab4.A getjsonAResult;
        
        public getjsonA1() {
        }
        
        public getjsonA1(Forms.ASMXServiceLab4.A getjsonAResult) {
            this.getjsonAResult = getjsonAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Forms.ASMXServiceLab4.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Forms.ASMXServiceLab4.SimplexSoap>, Forms.ASMXServiceLab4.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ASMXServiceLab4.sum1 Forms.ASMXServiceLab4.SimplexSoap.Add(Forms.ASMXServiceLab4.sum request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            Forms.ASMXServiceLab4.sum inValue = new Forms.ASMXServiceLab4.sum();
            inValue.x = x;
            inValue.y = y;
            Forms.ASMXServiceLab4.sum1 retVal = ((Forms.ASMXServiceLab4.SimplexSoap)(this)).Add(inValue);
            return retVal.sumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sum1> Forms.ASMXServiceLab4.SimplexSoap.AddAsync(Forms.ASMXServiceLab4.sum request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sum1> AddAsync(int x, int y) {
            Forms.ASMXServiceLab4.sum inValue = new Forms.ASMXServiceLab4.sum();
            inValue.x = x;
            inValue.y = y;
            return ((Forms.ASMXServiceLab4.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ASMXServiceLab4.concat1 Forms.ASMXServiceLab4.SimplexSoap.Concat(Forms.ASMXServiceLab4.concat request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Forms.ASMXServiceLab4.concat inValue = new Forms.ASMXServiceLab4.concat();
            inValue.s = s;
            inValue.d = d;
            Forms.ASMXServiceLab4.concat1 retVal = ((Forms.ASMXServiceLab4.SimplexSoap)(this)).Concat(inValue);
            return retVal.concatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.concat1> Forms.ASMXServiceLab4.SimplexSoap.ConcatAsync(Forms.ASMXServiceLab4.concat request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ASMXServiceLab4.concat1> ConcatAsync(string s, double d) {
            Forms.ASMXServiceLab4.concat inValue = new Forms.ASMXServiceLab4.concat();
            inValue.s = s;
            inValue.d = d;
            return ((Forms.ASMXServiceLab4.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ASMXServiceLab4.sumA1 Forms.ASMXServiceLab4.SimplexSoap.Sum(Forms.ASMXServiceLab4.sumA request) {
            return base.Channel.Sum(request);
        }
        
        public Forms.ASMXServiceLab4.A Sum(Forms.ASMXServiceLab4.A a1, Forms.ASMXServiceLab4.A a2) {
            Forms.ASMXServiceLab4.sumA inValue = new Forms.ASMXServiceLab4.sumA();
            inValue.a1 = a1;
            inValue.a2 = a2;
            Forms.ASMXServiceLab4.sumA1 retVal = ((Forms.ASMXServiceLab4.SimplexSoap)(this)).Sum(inValue);
            return retVal.sumAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumA1> Forms.ASMXServiceLab4.SimplexSoap.SumAsync(Forms.ASMXServiceLab4.sumA request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumA1> SumAsync(Forms.ASMXServiceLab4.A a1, Forms.ASMXServiceLab4.A a2) {
            Forms.ASMXServiceLab4.sumA inValue = new Forms.ASMXServiceLab4.sumA();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((Forms.ASMXServiceLab4.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ASMXServiceLab4.sumjson1 Forms.ASMXServiceLab4.SimplexSoap.Adds(Forms.ASMXServiceLab4.sumjson request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            Forms.ASMXServiceLab4.sumjson inValue = new Forms.ASMXServiceLab4.sumjson();
            inValue.x = x;
            inValue.y = y;
            Forms.ASMXServiceLab4.sumjson1 retVal = ((Forms.ASMXServiceLab4.SimplexSoap)(this)).Adds(inValue);
            return retVal.sumjsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumjson1> Forms.ASMXServiceLab4.SimplexSoap.AddsAsync(Forms.ASMXServiceLab4.sumjson request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ASMXServiceLab4.sumjson1> AddsAsync(int x, int y) {
            Forms.ASMXServiceLab4.sumjson inValue = new Forms.ASMXServiceLab4.sumjson();
            inValue.x = x;
            inValue.y = y;
            return ((Forms.ASMXServiceLab4.SimplexSoap)(this)).AddsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ASMXServiceLab4.getjsonA1 Forms.ASMXServiceLab4.SimplexSoap.GetA(Forms.ASMXServiceLab4.getjsonA request) {
            return base.Channel.GetA(request);
        }
        
        public Forms.ASMXServiceLab4.A GetA() {
            Forms.ASMXServiceLab4.getjsonA inValue = new Forms.ASMXServiceLab4.getjsonA();
            Forms.ASMXServiceLab4.getjsonA1 retVal = ((Forms.ASMXServiceLab4.SimplexSoap)(this)).GetA(inValue);
            return retVal.getjsonAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ASMXServiceLab4.getjsonA1> Forms.ASMXServiceLab4.SimplexSoap.GetAAsync(Forms.ASMXServiceLab4.getjsonA request) {
            return base.Channel.GetAAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ASMXServiceLab4.getjsonA1> GetAAsync() {
            Forms.ASMXServiceLab4.getjsonA inValue = new Forms.ASMXServiceLab4.getjsonA();
            return ((Forms.ASMXServiceLab4.SimplexSoap)(this)).GetAAsync(inValue);
        }
    }
}
